In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df_train = pd.read_csv('./input/train.csv')
data_train = np.array(df_train)
df_test = pd.read_csv('./input/test.csv')
data_test = np.array(df_test)

In [4]:
data_train

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [5]:
df_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:
df_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [7]:
df_test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [8]:
data_train[0]

array([1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
       'A/5 21171', 7.25, nan, 'S'], dtype=object)

In [9]:
df_train.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
len(data_train)

891

In [11]:
len(data_test)

418

In [12]:
tg = []
for i in range(0, len(data_train)):
    tg.append(data_train[i][1])
target = np.array(tg)
target

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [13]:
target2=pd.DataFrame(target)
target2.to_csv('target4.csv')

In [14]:
data_train.shape

(891, 12)

In [15]:
data_test.shape

(418, 11)

In [16]:
td=[]
for i in range(0, len(data_train)):
    td.append(data_train[i][2:])
for i in range(0, len(data_test)):
    td.append(data_test[i][1:])
traintestdata = np.array(td)
traintestdata

array([[3, 'Braund, Mr. Owen Harris', 'male', ..., 7.25, nan, 'S'],
       [1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', ..., 71.2833, 'C85', 'C'],
       [3, 'Heikkinen, Miss. Laina', 'female', ..., 7.925, nan, 'S'],
       ...,
       [3, 'Saether, Mr. Simon Sivertsen', 'male', ..., 7.25, nan, 'S'],
       [3, 'Ware, Mr. Frederick', 'male', ..., 8.05, nan, 'S'],
       [3, 'Peter, Master. Michael J', 'male', ..., 22.3583, nan, 'C']],
      dtype=object)

In [17]:
len(td)

1309

In [18]:
traintestdata[0]

array([3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0, 'A/5 21171',
       7.25, nan, 'S'], dtype=object)

In [19]:
traintestdata[1308]

array([3, 'Peter, Master. Michael J', 'male', nan, 1, 1, '2668', 22.3583,
       nan, 'C'], dtype=object)

In [20]:
td=[]
for i in range(0, len(traintestdata)):
    td.append(traintestdata[i][0]/2)
traintestdata_Pclass = np.array(td)
traintestdata_Pclass

array([1.5, 0.5, 1.5, ..., 1.5, 1.5, 1.5])

In [21]:
td=[]
for i in range(0, len(traintestdata)):
    if traintestdata[i][2] == 'male':
        td.append(0)
    else:
         td.append(1)   
traintestdata_sex = np.array(td)
traintestdata_sex

array([0, 1, 1, ..., 0, 0, 0])

In [22]:
str(data_train[5][5])

'nan'

In [23]:
type(data_train[5][5])

float

In [24]:
traintestdata[3][3]

35.0

In [25]:
td=[]

for i in range(0, len(traintestdata)):
    if str(traintestdata[i][3]) == 'nan':
        td.append(0.5)
    else:
        td.append(traintestdata[i][5])

traintestdata_age = np.array(td)
traintestdata_age

array([0. , 0. , 0. , ..., 0. , 0.5, 0.5])

In [26]:
td=[]
for i in range(0, len(traintestdata)):
        td.append((traintestdata[i][4]+traintestdata[i][5])/5)  
traintestdata_family = np.array(td)
traintestdata_family

array([0.2, 0.2, 0. , ..., 0. , 0. , 0.4])

In [27]:
td=[]
for i in range(0, len(traintestdata)): 
    if str(traintestdata[i][7]) == 'nan':
        td.append(0.2)           
    else:
        td.append(round(traintestdata[i][7])/50)     
        
traintestdata_fare = np.array(td)
traintestdata_fare

array([0.14, 1.42, 0.16, ..., 0.14, 0.16, 0.44])

In [28]:
td=[]
for i in range(0, len(traintestdata)):
    if traintestdata[i][9]=='S':
        td.append(0/2)          
    elif traintestdata[i][9]=='Q':
        td.append(1/2)          
    elif traintestdata[i][9]=='C':
        td.append(2/2)          
    else:
        td.append(3/2)  
        
traintestdata_embarked = np.array(td)
traintestdata_embarked

array([0., 1., 0., ..., 0., 0., 1.])

In [29]:
traintestdata2=[]

traintestdata２.append(traintestdata_Pclass)
traintestdata２.append(traintestdata_sex)
traintestdata２.append(traintestdata_age)
traintestdata２.append(traintestdata_family)
traintestdata２.append(traintestdata_fare)
traintestdata２.append(traintestdata_embarked)

traintestdata3=np.transpose(traintestdata2)
traintestdata3

array([[1.5 , 0.  , 0.  , 0.2 , 0.14, 0.  ],
       [0.5 , 1.  , 0.  , 0.2 , 1.42, 1.  ],
       [1.5 , 1.  , 0.  , 0.  , 0.16, 0.  ],
       ...,
       [1.5 , 0.  , 0.  , 0.  , 0.14, 0.  ],
       [1.5 , 0.  , 0.5 , 0.  , 0.16, 0.  ],
       [1.5 , 0.  , 0.5 , 0.4 , 0.44, 1.  ]])

In [30]:
traintestdata4=pd.DataFrame(traintestdata3)
traintestdata4.to_csv('traintestdata4.csv')

In [31]:
train = traintestdata3[:len(df_train)]
test = traintestdata3[len(df_train):]

In [32]:
y_train0 = target2
X_train0 = train
X_test0 = test

In [33]:
X = np.array(X_train0)
y = np.array(y_train0)